-- SKILLS TYPE
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Java');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('JavaScript');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('HTML');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('JSP');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('J2EE');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Angular JS');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('ReactJS');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Kubernetes');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Kotlin');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Docker');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('OpenShift');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Spring Boot');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('C++');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Cobol');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Oracle');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Postgres');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Ms SQL');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('DB2');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Microservice');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Dot Net');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('CSS');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('AUX / Unix');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Shell Scripts');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('PowerShell');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Linux');
INSERT INTO  SKILL_TYPE(DESCRIPTION) VALUES ('Windows');

-- LEVEL
INSERT INTO  SKILL_LEVEL(DESCRIPTION) VALUES ('Basic');
INSERT INTO  SKILL_LEVEL(DESCRIPTION) VALUES ('Advance');
INSERT INTO  SKILL_LEVEL(DESCRIPTION) VALUES ('Expert');

-- RODEL
INSERT INTO Consultant(COGNIZANT_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, DESIGNATION, EMAIL_ADDRESS, BENCH, PASSWORD, STATUS_CODE,MANAGER,AVATAR)
VALUES (2269180, 'Ramos', 'Rodelio','Santos','Lead Software Engineer','rodelio.ramos@cognizant.com',false,'Java@1234','A',true,'A');

INSERT INTO Skills(COGNIZANT_ID,SKILL_TYPE_ID,YEARS,lEVEL_TYPE)
VALUES (2269180,1,15,3);
INSERT INTO Skills(COGNIZANT_ID,SKILL_TYPE_ID,YEARS,lEVEL_TYPE)
VALUES (2269180,2,10,2);
INSERT INTO Skills(COGNIZANT_ID,SKILL_TYPE_ID,YEARS,lEVEL_TYPE)
VALUES (2269180,3,10,2);
INSERT INTO Skills(COGNIZANT_ID,SKILL_TYPE_ID,YEARS,lEVEL_TYPE)
VALUES (2269180,4,10,2);
INSERT INTO Skills(COGNIZANT_ID,SKILL_TYPE_ID,YEARS,lEVEL_TYPE)
VALUES (2269180,5,15,3);
INSERT INTO Skills(COGNIZANT_ID,SKILL_TYPE_ID,YEARS,lEVEL_TYPE)
VALUES (2269180,6,7,2);
INSERT INTO Skills(COGNIZANT_ID,SKILL_TYPE_ID,YEARS,lEVEL_TYPE)
VALUES (2269180,7,8,3);